# Generated by Django 4.2.4 on 2023-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ucord1', models.CharField(max_length=100)),
                ('ucord2', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField()),
                ('free_beds', models.IntegerField()),
            ],
        ),
    ]
